- hosts: web
  become: true

  tasks:
    - name: Instalar Docker
      dnf:
        name: docker
        state: present

    - name: Iniciar Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Remover container antigo Service A
      command: docker rm -f service-a
      ignore_errors: yes

    - name: Remover container antigo Service B
      command: docker rm -f service-b
      ignore_errors: yes

    - name: Fazer pull da imagem Service A
      command: docker pull ghcr.io/rafael-martins-a22308006/cloud_project_vicente_rafa/service-a:latest

    - name: Fazer pull da imagem Service B
      command: docker pull ghcr.io/rafael-martins-a22308006/cloud_project_vicente_rafa/service-b:latest

    - name: Correr Service A
      command: docker run -d --name service-a ghcr.io/rafael-martins-a22308006/cloud_project_vicente_rafa/service-a:latest

    - name: Correr Service B
      command: docker run -d --name service-b ghcr.io/rafael-martins-a22308006/cloud_project_vicente_rafa/service-b:latest